### ISSUE TITLE
Logarithmic curve reward model

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo#43]
The logarithmic reward model has two parts:

1. The x/oracle implementation side, which gives out tokens from the oracle module to validators in a loga model, where the validators with the least miss counters get the most rewards
2. The x/mint module implementation, which should control the creation of new tokens for these incentives

**Comment by adamewozniak** [comment]
Working on a graph to better describe the reward distribution

**Comment by adamewozniak** [comment]
Using the Formula `y=log(x+1)`, this is how our reward distribution should look:

<img width="918" alt="Screen Shot 2022-12-12 at 2 27 40 PM" src="https://user-images.githubusercontent.com/29418299/207168698-f858baf6-646c-47d0-88e9-1c395cb282ef.png">

Our algorithm should be: 

1. RewardDiv = Divide up the rewards in the oracle module by the amount of validators
2. Scale the X value from [0, 9] into [**Max Amount of Misses**, Min of Validator Miss Count`] linearly 
3. Loop through the validator set
   b. Using the Miss Counter as the X value, multiply `RewardDiv` by `y`

**Comment by rbajollari** [comment]
I think the last comment could be incorrect with this type of graph. The graph flattens as miss counters increase so it looks like the more poorly the validators vote collectively, the **less** aggressively worse validators get penalized.
